#!/usr/bin/with-contenv sh

INSTALL_JAVA8=${INSTALL_JAVA8:-false}
INSTALL_JAVA11=${INSTALL_JAVA11:-false}
INSTALL_JAVA17=${INSTALL_JAVA17:-true}

eval $(cat /etc/*release | grep ID)
if [ ! "$ID" = "alpine" ]; then
  exit 0
fi

echo '
-------------------------------------
Installing Java runtime
-------------------------------------'

if [ "$INSTALL_JAVA8" = true ] && [ ! -d "/usr/lib/jvm/java-1.8-openjdk" ]; then
  echo '
Installing Java 8...
-------------------------------------'
  apk add --no-cache openjdk8-jre
fi

if [ -d "/usr/lib/jvm/java-1.8-openjdk" ]; then
  echo '
-------------------------------------
Java 8 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA11" = true ] && [ ! -d "/usr/lib/jvm/java-11-openjdk" ]; then
  echo '
Installing Java 11...
-------------------------------------'
  apk add --no-cache openjdk11-jre-headless
fi

if [ -d "/usr/lib/jvm/java-11-openjdk" ]; then
  echo '
-------------------------------------
Java 11 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA17" = true ] && [ ! -d "/usr/lib/jvm/java-17-openjdk" ]; then
  echo '
Installing Java 17...
-------------------------------------'
  apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted openjdk17-jre-headless
fi

if [ -d "/usr/lib/jvm/java-17-openjdk" ]; then
  echo '
-------------------------------------
Java 17 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA8" = false ] && [ "$INSTALL_JAVA11" = false ] && [ "$INSTALL_JAVA17" = false ]; then
  echo 'Environment variables INSTALL_JAVA8, INSTALL_JAVA11 and INSTALL_JAVA17 have been set to false! Skipping Java runtime install...
-------------------------------------'
fi
