#!/usr/bin/with-contenv sh

USER_ID=${USER_ID:-1000}
GROUP_ID=${GROUP_ID:-1000}

echo '
-------------------------------------
Checking ownership of /crafty_web folder
-------------------------------------'

if [ "${FIX_OWNERSHIP:-true}" = true ]; then
    if [ ${USER_ID} != "1000" ]; then
        echo "USER_ID differs from default, adjusting ownership..."
        find /crafty_web -user 1000 -exec chown -h crafty {} \;
    fi

    if [ ${GROUP_ID} != "1000" ]; then
        echo "GROUP_ID differs from default, adjusting ownership..."
        find /crafty_web -group 1000 -exec chgrp -h crafty {} \;
    fi
else
    echo "FIX_OWNERSHIP was disabled, doing nothing."
fi

echo "
Done.
-------------------------------------
"
